#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

script_dir=$(cd $(dirname $0); pwd -P)
current_dir=$(pwd -P)

function run_stack_command()
{
  stack $*
}

if [[ $# -lt 1 ]]; then
  echo 'Usage: run-stack <stack-command-arg-0> .. <stack-command-arg-N-1>'
  exit 1
fi

echo "cmd: stack $*"

# TODO: Avoid running find twice!
if [[ -z $(find . -name 'stack.yaml' -maxdepth 1) ]]; then
  find . -name 'stack.yaml' -maxdepth 1 | while read yaml_path; do
      yaml_dir=$(cd $(dirname $yaml_path); pwd -P)
      echo "dir: $yaml_dir"
      pushd $yaml_dir > /dev/null
      run_stack_command $*
      popd > /dev/null
  done
else
  echo "dir: $current_dir"
  run_stack_command $*
fi
