#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

script_dir=$(cd $(dirname $0); pwd -P)
current_dir=$(pwd -P)

function run_stack_command()
{
  stack $*
}

if [[ $# -lt 1 ]]; then
  echo 'Usage: run-stack <stack-command-arg-0> .. <stack-command-arg-N-1>'
  exit 1
fi

echo "cmd: stack $*"

if [ -e stack.yaml ]; then
  echo dir: $current_dir
  run_stack_command $*
  exit 0
fi

stack_yaml_paths=($(find . -maxdepth 2 -name 'stack.yaml'))
if [ -z ${stack_yaml_paths+x} ]; then
  echo No stack.yaml files found
  exit 1
fi

for stack_yaml_path in "${stack_yaml_paths[@]}"; do
  stack_yaml_dir=$(cd $(dirname $stack_yaml_path); pwd -P)
  echo "dir: $stack_yaml_dir"
  pushd $stack_yaml_dir > /dev/null
  run_stack_command $*
  popd > /dev/null
done
